Models/MyTask.cs
using System.ComponentModel.DataAnnotations;

namespace Hw57.Models;

public class MyTask
{
    public int Id { get; set; }
    [Required(ErrorMessage = "Заполните ячейку")]
    public string Name { get; set; }
    [Required(ErrorMessage = "Заполните ячейку")]
    public string Priority { get; set; }
    public string Status { get; set; }
    [Required(ErrorMessage = "Заполните ячейку")]
    public DateTime? DateOfCreation { get; set; }
    public DateTime? DateOfOpening { get; set; }
    public DateTime? DateOfClosing { get; set; }
    [Required(ErrorMessage = "Заполните ячейку")]
    public string Description { get; set; }
    
    public int CreatorId { get; set; }
    public User? Creator { get; set; }
    public int? ExecutorId { get; set; }
    public User? Executor { get; set; }
}

Controllers/MyTaskController.cs
using Hw57.Models;
using Hw57.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hw57.Controllers;

public class MyTaskController : Controller
{
    public MyTaskContext _context;
    private readonly UserManager<User> _userManager;
    public TaskService _service;
    private readonly SignInManager<User> _signInManager;

    public MyTaskController(MyTaskContext context, UserManager<User> userManager, SignInManager<User> signInManager, TaskService service)
    {
        _context = context;
        _userManager = userManager;
        _signInManager = signInManager;
        _service = service;
    }
    [Authorize]
    public async Task<IActionResult> Index(string? priority, string? status, string? titleSearch, DateTime? dateFrom, DateTime? dateTo, string? wordFilter,TaskSortState sortState = TaskSortState.NameAsc, int page = 1)
    {
        IQueryable<MyTask> filteredTasks = _context.Tasks;
        ViewBag.Priorities = new List<string>() {"Высокий", "Средний", "Низкий" };
        ViewBag.Statuses = new List<string>() { "Новая", "Открыта", "Закрыта" };
        if (!string.IsNullOrEmpty(ViewBag.Priority))
        {
            priority = ViewBag.Priority;
        }
        if (!string.IsNullOrEmpty(ViewBag.Status))
        {
            status = ViewBag.Status;
        }
        if (!string.IsNullOrEmpty(ViewBag.TitleSearch))
        {
            titleSearch = ViewBag.TitleSearch;
        }
        if (!string.IsNullOrEmpty(ViewBag.WordFilter))
        {
            wordFilter = ViewBag.WordFilter;
        }
        if (!string.IsNullOrEmpty(ViewBag.DateTo))
        {
            dateTo = ViewBag.DateTo;
        }
        if (!string.IsNullOrEmpty(ViewBag.DateFrom))
        {
            dateFrom = ViewBag.DateFrom;
        }
        if (!string.IsNullOrEmpty(priority))
            filteredTasks = filteredTasks.Where(t => t.Priority == priority);
        if (!string.IsNullOrEmpty(status))
            filteredTasks = filteredTasks.Where(t => t.Status == status);
        if (!string.IsNullOrEmpty(titleSearch))
            filteredTasks = filteredTasks.Where(t => t.Name.Equals(titleSearch));
        if (!string.IsNullOrEmpty(wordFilter))
            filteredTasks = filteredTasks.Where(t => t.Description.Contains(wordFilter.ToLower()));
        if (dateFrom.HasValue)
        {
            dateFrom = dateFrom.Value.ToUniversalTime();
            filteredTasks = filteredTasks.Where(t => t.DateOfCreation >= dateFrom);
        }
        if (dateTo.HasValue)
        {
            dateTo = dateTo.Value.ToUniversalTime();
            filteredTasks = filteredTasks.Where(t => t.DateOfCreation <= dateTo);
        }

        var tasks = filteredTasks.ToList();
        ViewBag.NameSort = sortState == TaskSortState.NameAsc ? TaskSortState.NameDesc : TaskSortState.NameAsc;
        ViewBag.PrioritySort = sortState == TaskSortState.PriorityAsc ? TaskSortState.PriorityDesc : TaskSortState.PriorityAsc;
        ViewBag.StatusSort = sortState == TaskSortState.StatusAsc ? TaskSortState.StatusDesc : TaskSortState.StatusAsc;
        ViewBag.DateOfCreationSort = sortState == TaskSortState.DateOfCreationAsc ? TaskSortState.DateOfCreationDesc : TaskSortState.DateOfCreationAsc;
        switch (sortState)
        {
            case TaskSortState.NameAsc:
                tasks = tasks.OrderBy(t => t.Name).ToList();
                break;
            case TaskSortState.NameDesc:
                tasks = tasks.OrderByDescending(t => t.Name).ToList();
                break;
            case TaskSortState.PriorityAsc:
                tasks = tasks.OrderBy(t => SortFields(t.Priority)).ToList();
                break;
            case TaskSortState.PriorityDesc:
                tasks = tasks.OrderByDescending(t => SortFields(t.Priority)).ToList();
                break;
            case TaskSortState.StatusAsc:
                tasks = tasks.OrderBy(t => SortFields(t.Status)).ToList();
                break;
            case TaskSortState.StatusDesc:
                tasks = tasks.OrderByDescending(t => SortFields(t.Status)).ToList();
                break;
            case TaskSortState.DateOfCreationAsc:
                tasks = tasks.OrderBy(t => t.DateOfCreation).ToList();
                break;
            case TaskSortState.DateOfCreationDesc:
                tasks = tasks.OrderByDescending(t => t.DateOfCreation).ToList();
                break;
            default:
                tasks = tasks.OrderBy(t => t.Name).ToList();
                break;
        }
        int pageSize = 5;
        int count = tasks.Count();
        var items = tasks.Skip((page - 1) * pageSize).Take(pageSize);
        PageViewModel pvm = new PageViewModel(count, page, pageSize);
        TaskIndexViewModel tivm = new TaskIndexViewModel()
        {
            PageViewModel = pvm,
            Tasks = items
        };
        ViewBag.CurrentSort = sortState;
        ViewBag.CurrentFilter = tasks;
        ViewBag.Priority = priority;
        ViewBag.Status = status;
        ViewBag.TitleSearch = titleSearch;
        ViewBag.WordFilter = wordFilter;
        if (dateTo.HasValue)
        {
            
            ViewBag.DateTo = dateTo.Value.ToUniversalTime();
        }

        if (dateFrom.HasValue)
        {
            
            ViewBag.DateFrom = dateFrom.Value.ToUniversalTime();
        }
        ViewBag.Priorities = new List<string>() {"Высокий", "Средний", "Низкий" };
        int? userId = Convert.ToInt32(_userManager.GetUserId(User));
        if (userId != null)
        {
            ViewBag.UserId = userId;
        }
        return View(tivm);
    }
    [Authorize]
    public async Task<IActionResult> Create()
    {
        ViewBag.Priorities = new List<string>() {"Высокий", "Средний", "Низкий" };
        string userId = _userManager.GetUserId(User);
        User user = await _userManager.FindByIdAsync(userId);
        ViewBag.User = user;
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Create(MyTask task)
    {
        
        ViewBag.Priorities = new List<string>(){"Высокий", "Средний", "Низкий" };
        int? userId = Convert.ToInt32(_userManager.GetUserId(User));
        User? user = await _context.Users.FirstOrDefaultAsync(u => u.Id == userId);
        ViewBag.User = user;
        if (await _context.Tasks.AnyAsync(t => t.Name == task.Name) && _context.Tasks.Any(t => t.ExecutorId == userId))
        {
            ModelState.AddModelError("", "Задача с таким название уже существует!");
            return View(task);
        }
        if (ModelState.IsValid)
        {
            task.DateOfCreation = DateTime.Now.ToUniversalTime();
            await _service.AddTask(task);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return View(task);
    }
    [Authorize]
    [ResponseCache(Duration = 120, Location = ResponseCacheLocation.Any)]
    public async Task<IActionResult> MyTask(int id)
    {
        var task = await _service.GetTask(id);
        if (task == null)
        {
            return NotFound();
        }
        int? userId = Convert.ToInt32(_userManager.GetUserId(User));
        if (userId != null)
        {
            ViewBag.UserId = userId;
        }
        return View(task);
    }
    [Authorize]
    public IActionResult Open(int? id)
    {
        if (id != null)
        {
            MyTask task = _context.Tasks.FirstOrDefault(t => t.Id == id);
            int userId = Convert.ToInt32(_userManager.GetUserId(User));
            if (task.Status == "Новая" && task.ExecutorId != null && (task.ExecutorId == userId || User.IsInRole("admin")))
            {
                task.DateOfOpening = DateTime.UtcNow;
                task.Status = "Открыта";
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        return NotFound();
    }
    [Authorize]
    public IActionResult Close(int? id)
    {
        if (id != null)
        {
            MyTask task = _context.Tasks.FirstOrDefault(t => t.Id == id);
            int userId = Convert.ToInt32(_userManager.GetUserId(User));
            if (task.Status=="Открыта" && task.ExecutorId != null && (task.ExecutorId == userId || User.IsInRole("admin")))
            {
                task.DateOfClosing = DateTime.UtcNow;
                task.Status = "Закрыта";
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        return NotFound();
    }
    [Authorize]
    [HttpGet]
    [ActionName("Delete")]
    [ResponseCache(Duration = 200, Location = ResponseCacheLocation.Any)]
    public async Task<IActionResult> ConfirmDelete(int? id)
    {
        if (id != null)
        {
            MyTask task = await _context.Tasks.FirstOrDefaultAsync(p => p.Id == id);
            string userId = _userManager.GetUserId(User);
            User user = await _userManager.FindByIdAsync(userId);
            if (task != null && (task.CreatorId == user.Id || User.IsInRole("admin")))
            {
                if (!task.Status.Equals("Открыта"))
                    return View(task);
                else
                    return RedirectToAction("Index");
            }
                
        }
        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id != null)
        {
            await _service.RemoveTask(id);
            return RedirectToAction("Index");
        }
        return NotFound();
    }
    [Authorize]
    public IActionResult Edit(int? id)
    {
        if (id != null)
        {
            MyTask myTask = _context.Tasks.FirstOrDefault(p => p.Id == id);
            int userId = Convert.ToInt32(_userManager.GetUserId(User));

Views/MyTask/Create.cshtml
@model MyTask

@{
    ViewBag.Title = "Task Create";
    Layout = "_Layout";
}

<h3 class="text-center mt-4">@Localizer["FillForm"]</h3>
<form asp-action="Create" method="post" class="connection-form">
@Html.ValidationSummary(true)
    <div class="row  mt-5">
        <div class="col col-6 mx-auto">
            <div class="mt-3 row">
                <label asp-for="CreatorId">@Localizer["NameOfCreator"]<span class="text-danger ms-2" asp-validation-for="CreatorId"></span></label>
                <div class="input-group">
                    <input disabled type="text" value="@ViewBag.User.UserName" class="form-control">
                    <input asp-for="CreatorId" type="hidden" value="@ViewBag.User.Id" class="form-control rounded-1  mt-3" placeholder="введите имя">
                </div>
            </div>
            <div class="mt-3 row">
                <label for="name">@Localizer["NameOfTask"]<span class="text-danger ms-2" asp-validation-for="Name"></span></label>
                <div class="input-group">
                    <input asp-for="Name" type="text" class="form-control rounded-1  mt-3" placeholder="введите название" id="name">
                </div>
            </div>
            <div class="mt-3">
                <label for="Priority">@Localizer["Priority"]<span class="text-danger ms-2" asp-validation-for="Priority"></span></label>
                <select asp-for="Priority" name="Priority" class="form-select mt-3" id="Priority">
                    <option selected disabled="disabled">Выберите приоритет</option>
                    @foreach (var priority in ViewBag.Priorities)
                    {
                        <option value="@priority">@priority</option>
                    }
                </select>
            </div>
            <div class="mt-3">
                <label for="descr">@Localizer["Description"]<span class="text-danger ms-2" asp-validation-for="Description"></span></label>
                <textarea id="descr" placeholder="Подробное описание" class="form-control form-control-lg mt-3  h-100" asp-for="Description" type="text" rows="3"></textarea>
            </div>
            <input asp-for="Status" value="Новая" type="hidden"/>
            <input asp-for="DateOfCreation" value="@DateTime.UtcNow" type="hidden"/>
            <button type="submit" class="btn btn-success mt-5 px-3">@Localizer["AddTask"]</button>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/MyTask/Delete.cshtml
@model MyTask

@{
    ViewBag.Title = "Удаление продукта";
}
 
<div class="container text-center pt-5 ">
    <div class="row">
        <div class="col-4 mx-auto border border-4 py-3">
            <dl class="dl-horizontal ">
                <dt>@Localizer["Name"]</dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
            
                <dt>@Localizer["Priority"]</dt>
                <dd>
                    @Html.DisplayFor(model => model.Priority)
                </dd>
            
                <dt>@Localizer["State"]</dt>
                <dd>
                    @Html.DisplayFor(model => model.Status)
                </dd>
            </dl>
            <form asp-controller="MyTask" asp-action="Delete" method="post">
                <button type="submit" class="btn btn-danger rounded-0 px-3 py-2 ">Удалить</button>
            </form>
        </div>
    </div>
</div>

Views/MyTask/Edit.cshtml
@model MyTask

@{
    ViewBag.Title = "EditMyTask";
    Layout = "_Layout";
}

<h2>@Localizer["Edit"]</h2>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" asp-controller="MyTask" method="post">
            <input asp-for="Id" type="hidden" />
            <input asp-for="CreatorId" type="hidden" />
            <input asp-for="Status" type="hidden" />
            <input asp-for="ExecutorId" type="hidden" />
            <input asp-for="DateOfClosing" type="hidden" />
            <input asp-for="DateOfCreation" type="hidden" />
            <input asp-for="DateOfOpening" type="hidden" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">@Localizer["NameOfTask"]</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority">@Localizer["Priority"]<span class="text-danger ms-2" asp-validation-for="Priority"></span></label>
                <select asp-for="Priority" name="Priority" class="form-select mt-3" id="Priority">
                    <option selected disabled="disabled">Выберите приоритет</option>
                    @foreach (var priority in ViewBag.Priorities)
                    {
                        <option value="@priority">@priority</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">@Localizer["Desc"]</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">@Localizer["Button"]</button>
        </form>
    </div>
</div>

@section Scripts{
    
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/MyTask/Index.cshtml
@model TaskIndexViewModel

@{
    ViewBag.Title = "Tasks";
    Layout = "_Layout";
}

<h2>@Localizer["ListOfTasks"]</h2>

<div class="row table_section">
    <form asp-action="Index" method="get" class="mb-4">
        <div class="row">
            <div class="col-md-3 mb-2">
                <label for="titleSearch" class="form-label">@Localizer["Title"]:</label>
                <input type="text" id="titleSearch" name="titleSearch" class="form-control" placeholder="@Localizer["SearchTitle"]">
            </div>
            <div class="col-md-3 mb-2">
                <label for="dateFrom" class="form-label">@Localizer["DateFrom"]:</label>
                <input type="date" id="dateFrom" name="dateFrom" class="form-control">
            </div>
            <div class="col-md-3 mb-2">
                <label for="dateTo" class="form-label">@Localizer["DateTo"]:</label>
                <input type="date" id="dateTo" name="dateTo" class="form-control">
            </div>
            <div class="col-md-3 mb-2">
                <label for="wordFilter" class="form-label">@Localizer["FilterByDesc"]:</label>
                <input type="text" id="wordFilter" name="wordFilter" class="form-control" placeholder="@Localizer["SearchDesc"]">
            </div>
            <div class="col-md-4 mb-2">
                <label for="priority" class="form-label">@Localizer["Priority"]</label>
                <select id="priority" name="priority" class="form-select">
                    <option value="">@Localizer["AllPriorities"]</option>
                    @foreach (var priority in ViewBag.Priorities)
                    {
                        <option value="@priority">@priority</option>
                    }
                </select>
            </div>
            
            <div class="col-md-4 mb-2">
                <label for="status" class="form-label">@Localizer["State"]</label>
                <select id="status" name="status" class="form-select">
                    <option value="">@Localizer["AllStates"]</option>
                    @foreach (var statuses in ViewBag.Statuses)
                    {
                        <option value="@statuses">@statuses</option>
                    }
                </select>
            </div>
            
            <div class="col-md-3 d-flex align-items-end">
                <button type="submit" class="btn btn-primary my-2">@Localizer["ApplyFilter"]</button>
            </div>
        </div>
    </form>
    @if (@Model.Tasks.Count() == 0)
    {
        <p>@Localizer["LackOfTasks"]</p>
    }
    else
    {
        <table class="table table-light table-striped">
            <thead>
            <tr>
                <th>Номер</th>
                <th><a asp-action="Index"
                       asp-route-sortState="@ViewBag.NameSort"
                       asp-route-priority="@ViewBag.Priority"
                       asp-route-status="@ViewBag.Status"
                       asp-route-titleSearch="@ViewBag.TitleSearch"
                       asp-route-dateFrom="@ViewBag.DateFrom"
                       asp-route-dateTo="@ViewBag.DateTo"
                       asp-route-wordFilter="@ViewBag.WordFilter">@Localizer["Title"]</a></th>
                <th><a asp-action="Index" 
                       asp-route-sortState="@ViewBag.PrioritySort"
                       asp-route-priority="@ViewBag.Priority"
                       asp-route-status="@ViewBag.Status"
                       asp-route-titleSearch="@ViewBag.TitleSearch"
                       asp-route-dateFrom="@ViewBag.DateFrom"
                       asp-route-dateTo="@ViewBag.DateTo"
                       asp-route-wordFilter="@ViewBag.WordFilter">@Localizer["Priority"]</a></th>
                <th><a asp-action="Index" 
                       asp-route-sortState="@ViewBag.StatusSort"
                       asp-route-priority="@ViewBag.Priority"
                       asp-route-status="@ViewBag.Status"
                       asp-route-titleSearch="@ViewBag.TitleSearch"
                       asp-route-dateFrom="@ViewBag.DateFrom"
                       asp-route-dateTo="@ViewBag.DateTo"
                       asp-route-wordFilter="@ViewBag.WordFilter">@Localizer["State"]</a></th>
                <th><a asp-action="Index" 
                       asp-route-sortState="@ViewBag.DateOfCreationSort"
                       asp-route-priority="@ViewBag.Priority"
                       asp-route-status="@ViewBag.Status"
                       asp-route-titleSearch="@ViewBag.TitleSearch"
                       asp-route-dateFrom="@ViewBag.DateFrom"
                       asp-route-dateTo="@ViewBag.DateTo"
                       asp-route-wordFilter="@ViewBag.WordFilter">@Localizer["DateOfCreation"]</a></th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var task in @Model.Tasks)
            {
                <tr>
                    <td>@task.Id</td>
                    <td>@task.Name</td>
                    <td class="@PriorityColor(@task.Priority)">@task.Priority</td>
                    <td>@task.Status</td>
                    <td>@task.DateOfCreation</td>
                    <td>
                        @Html.ValidationSummary(true)
                        @if (task.Status == "Новая" && task.ExecutorId != null && (task.ExecutorId == ViewBag.UserId || User.IsInRole("admin")))
                        {
                            <a asp-controller="MyTask" asp-action="Open" asp-route-id="@task.Id" type="button" class="btn btn-success rounded-0 px-3 py-2 ">@Localizer["Open"]</a>
                        }
                        @if (task.Status == "Открыта" && task.ExecutorId != null && (task.ExecutorId == ViewBag.UserId || User.IsInRole("admin")))
                        {
                            <a asp-controller="MyTask" asp-action="Close" asp-route-id="@task.Id" type="button" class="btn btn-primary rounded-0 px-3 py-2 ">@Localizer["Close"]</a>
                        }
                        <a asp-controller="MyTask" asp-action="MyTask" asp-route-id="@task.Id" type="button" class="btn btn-warning rounded-0 px-3 py-2 ">@Localizer["Detail"]</a>
                        @if (task.Status != "Открыта" && (task.CreatorId == ViewBag.UserId || User.IsInRole("admin")))
                        {
                            <a asp-controller="MyTask" asp-action="Delete" asp-route-id="@task.Id" type="button" class="btn btn-danger rounded-0 px-3 py-2 ">@Localizer["Delete"]</a>
                        }
                    </td>

                </tr>
            }
            </tbody>
        </table>
        <div class="col-4 mx-auto text-center">
            @if (Model.PageViewModel.HasPreviousPage)
            { <a class="btn btn-primary me-4" asp-action="Index"
                 asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
                 asp-route-sortState="@ViewBag.CurrentSort"
                 asp-route-priority="@ViewBag.Priority"
                 asp-route-status="@ViewBag.Status"
                 asp-route-titleSearch="@ViewBag.TitleSearch"
                 asp-route-dateFrom="@ViewBag.DateFrom"
                 asp-route-dateTo="@ViewBag.DateTo"
                 asp-route-wordFilter="@ViewBag.WordFilter">@Localizer["Previous"]</a> }
            @if (Model.PageViewModel.HasNextPage)
            { <a class="btn btn-primary ms-4" asp-action="Index"
                 asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
                 asp-route-sortState="@ViewBag.CurrentSort"
                 asp-route-priority="@ViewBag.Priority"
                 asp-route-status="@ViewBag.Status"
                 asp-route-titleSearch="@ViewBag.TitleSearch"
                 asp-route-dateFrom="@ViewBag.DateFrom"
                 asp-route-dateTo="@ViewBag.DateTo"
                 asp-route-wordFilter="@ViewBag.WordFilter">@Localizer["Next"]</a> }
        </div>
    }
</div>


@functions{
    public string PriorityColor(string priority)
    {
        switch (priority)
        {
            case "Высокий":
                return "text-danger";
            case "Средний":
                return "text-primary";
            case "Низкий":
                return "text-success";
            default:
                return "";
        }
    }
}

Views/MyTask/MyTask.cshtml
@model MyTask

@{
    ViewBag.Title = "Task";
    Layout = "_Layout";
}

<div class="container-lg border border-2">
    <div class="row row-cols-2 mt-4">
        <div class="col col-12">
            <h2>@Model.Name</h2>
        </div>
        <div class="col col-5">
            <div class="row row-cols-2">
                <div class="col col-6 pb-5 border border-2">
                    <h5 class="mt-4">@Localizer["NameOfCreator"]</h5>
                    @if (Model.ExecutorId != null)
                    {
                        <h5 class="mt-4">@Localizer["NameOfExecutor"]</h5>
                    }
                    <h5 class="mt-4">@Localizer["State"]</h5>
                    <h5 class="mt-4">@Localizer["Priority"]</h5>
                    <h5 class="mt-4">@Localizer["Number"]</h5>
                    <h5 class="mt-4">@Localizer["DateOfCreation"]</h5>
                    @if (!Model.Status.Equals("Новая"))
                    {
                        <h5 class="mt-4">@Localizer["Date"]
                            @if (Model.Status.Equals("Закрыта"))
                            {
                                <span>@Localizer["DateOfClosin"]</span>
                            }
                            else if (Model.Status.Equals("Открыта"))
                            {
                                <span>@Localizer["DateOfOpening"]</span>
                            }
                        </h5>
                    }
                </div>
                <div class="col col-6 pb-5 border border-2">
                    <h5 class="mt-4">@Model.Creator.UserName</h5>
                    @if (Model.ExecutorId != null)
                    {
                        <h5 class="mt-4">@Model.Executor.UserName</h5>
                    }
                    <h5 class="mt-4">@Model.Status</h5>
                    <h5 class="mt-4 @PriorityColor(@Model.Priority)">@Model.Priority</h5>
                    <h5 class="mt-4">@Model.Id</h5>
                    <h5 class="mt-4">@Model.DateOfCreation</h5>
                    @if (!Model.Status.Equals("Новая"))
                    {
                        <h5 class="mt-4">
                            @if (Model.Status.Equals("Закрыта"))
                            {
                                <span>@Model.DateOfClosing</span>
                            }
                            else if (Model.Status.Equals("Открыта"))
                            {
                                <span>@Model.DateOfOpening</span>
                            }
                            else
                            {
                                <span>@Model.DateOfCreation</span>
                            }
                        </h5>
                    }
                </div>
                <div class="col col-12 py-5 border border-2">
                    @if (Model.Status.Equals("Новая") && Model.ExecutorId != null && (Model.ExecutorId == ViewBag.UserId || User.IsInRole("admin"))) { <a asp-controller="MyTask" asp-action="Open" asp-route-id="@Model.Id" type="button" class="btn btn-success rounded-0 px-3 py-2 ">@Localizer["Open"]</a> }
                    @if (Model.Status.Equals("Открыта") && Model.ExecutorId != null && (Model.ExecutorId == ViewBag.UserId || User.IsInRole("admin"))) { <a asp-controller="MyTask" asp-action="Close" asp-route-id="@Model.Id" type="button" class="btn btn-primary rounded-0 px-3 py-2 ">@Localizer["Close"]</a> }
                    @if(!Model.Status.Equals("Открыта") && (Model.CreatorId == ViewBag.UserId || User.IsInRole("admin"))){ <a asp-controller="MyTask" asp-action="Delete" asp-route-id="@Model.Id" type="button" class="btn btn-danger rounded-0 px-3 py-2 ">@Localizer["Delete"]</a> }
                    @if(Model.CreatorId == ViewBag.UserId || User.IsInRole("admin")){ <a asp-controller="MyTask" asp-action="Edit" asp-route-id="@Model.Id" type="button" class="btn btn-danger rounded-0 px-3 py-2 ">@Localizer["Edit"]</a> }
                    @if(Model.ExecutorId == null){ <a asp-controller="MyTask" asp-action="TakeTask" asp-route-id="@Model.Id" type="button" class="btn btn-danger rounded-0 px-3 py-2 ">@Localizer["Take"]</a> }
                </div>
            </div>
        </div>
        <div class="col col-7 pt-4 border border-2">
            <h3 class="mt-1">@Localizer["Desc"]</h3>
            <p class="fs-2">@Model.Description</p>
        </div>
    </div>
</div>

@functions{
    public string PriorityColor(string priority)
    {
        switch (priority)
        {
            case "Высокий":
                return "text-danger";
            case "Средний":
                return "text-primary";
            case "Низкий":
                return "text-success";
            default:
                return "";
        }
    }
}